### ISSUE TITLE
Markbook Column Ordering is not working properly

### ISSUE THREAD

**Issue by jian118** [GibbonEdu/core#790] opened 2019-02-11 03:26 UTC
Markbook column order is messed up since minSequenceNumber is always 0. 

In modules/Markbook/src/MarkbookView.php 
Line 61 change to 
```
protected $minSequenceNumber = 99999;
```

Line 334 add 
```
// Grab the minimum sequenceNumber for the current page set, to pass to markbook_viewAjax.php
$this->minSequenceNumber = min($this->minSequenceNumber, $columnData['sequenceNumber']);
```
Line 325-328 remove as it's checking empty $this->columns

 -----

Another issue is that when term filtering is applied, the sequenceNumber gets overwritten by the term table. 
In src\Domain\Markbook\MarkbookColumnGateway.php Line 47 change to the following
```
->cols(['*','gibbonMarkbookColumn.name as name','gibbonMarkbookColumn.sequenceNumber as sequenceNumber'])
```

-----
Ordering made before this fix would require manual fixing in the database

**Comment by jian118** [comment] 2019-02-11 03:41
SQL to reset ordering by class. 
```
SET @count:=0;
update gibbonMarkbookColumn
set `sequenceNumber`=@count:=@count+1
where `gibbonCourseClassID` = 56
```

**Comment by SKuipers** [comment] 2019-02-14 07:18
Hi @jian118 

It looks like you've put together some great fixes. When you say the column order is messed up, are you able to share more info or screenshots on how to reproduce that? I've checked with existing installs as well as a fresh install and the column ordering (default and drag-drop) appears to be working as expected 🤔

**Comment by jian118** [comment] 2019-02-14 07:21
It only happen when you exceed one page which is more than 25 columns

**Comment by jian118** [comment] 2019-02-20 01:09
hi @SKuipers 

Below is the screen capture.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8830491/53058623-c4324380-34ee-11e9-9032-42d89b055b5e.gif)

1. go to 2nd page
2. click on sorting tab
3. refresh page
4. go back to first page

The sequence was initially test1, 2....25. Now its 1,26,2,27,3,28,4,29

**Comment by SKuipers** [comment] 2019-02-20 05:47
Aha, thanks for this, I can reproduce it now too 👍  Are you interested in putting your fixes together as a [pull request](https://github.com/GibbonEdu/core/blob/master/docs/CONTRIBUTING.md#how-to-submit-a-pull-request) for our development branch v18? I think the reset button may be a good way to go (vs the database call, which would change all the orders regardless of if they got messed up). Otherwise, let me know and I'll work to add these changes in. Thanks!

**Comment by SKuipers** [comment] 2019-03-26 05:46
Thanks again for your fix! Looks like this is resolved and working well, I'm going to close the issue. Feel free to put in any more issues or PRs if you spot other bugs.

**Closed by SKuipers** 2019-03-26 05:46 UTC
Labels: bug
