### ISSUE TITLE
Error after installation with sample data v14.0.01

### ISSUE THREAD

**Issue by bobkee** [GibbonEdu/core#362] opened 2017-10-07 17:01 UTC
After signing in there is an error in the first page concerning the timetables. It says: 
Notice: A non well formed numeric value encountered in C:\xampp\htdocs\Gibbon\modules\Timetable\moduleFunctions.php on line 842

I went to what I believe is line 842, it says:
 while ($time <= $timeEnd and $spinControl < (23 - substr($timeStart, 0, 5))) {

## Expected Behavior
to see the timetable data

## Actual Behavior
error as above

## Steps to Reproduce

1.Install xampp
2.Install Gibbon
3.Go through setup
4.Login

## Your Environment

* Gibbon Version: 14.0.01
* Google Chrome

**Comment by rossdotparker** [comment] 2017-10-10 00:24
Hi bobkee, we will take a look at this notice issue later on today and try to get it resolved. In the meantime, please note that PHP Notices represent minor coding issues, and are not errors in the sense that they do not have a negative impact on how the code runs. Our advice would be to adjust your PHP settings in order to not show notices (or errors) on screen to users. They can still be logged for you to see. Hope this helps. Ross

**Comment by rossdotparker** [comment] 2017-10-11 13:34
Hi bobkee, I've had a look into this, and I cannot reproduce the issue. If you can add the following code above line 842, and email us the output it adds to your page, that would help us to narrow in on the issue:

echo $time.'<br>';
echo $timeEnd.'<br>';
echo $spinControl .'<br>';
echo $timeStart.'<br>';

Thanks,

Ross

**Comment by jimbo8098** [comment] 2017-10-22 11:11
Hi @bobkee , I've just made a new installation from v14.0.01 and I didn't have any problems seeing the data. Here's some output for comparison to your XAMMP installation:

`root@nodejs-512mb-lon1-01:/var/www/gibbonv15# php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
`

`root@nodejs-512mb-lon1-01:/var/www/gibbonv15# apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02
`

`root@nodejs-512mb-lon1-01:/var/www/gibbonv15# uname -a
Linux nodejs-512mb-lon1-01 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`

`root@nodejs-512mb-lon1-01:/var/www/gibbonv15# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 56856
Server version: 10.2.8-MariaDB-10.2.8+maria~xenial-log mariadb.org binary distribution
`

`root@nodejs-512mb-lon1-01:/var/www/gibbonv15# date
Sun Oct 22 11:09:34 UTC 2017
`

I suspect the problem here is maybe to do with the timezone. Which timezone did you use for your installation?

**Comment by luminkhant** [comment] 2017-11-17 04:16
Change this line at Timetable/moduleFunction.php
         while ($time <= $timeEnd and $spinControl < (23 - substr($timeStart, 0, 5))) 
to this 
         while ($time <= $timeEnd and $spinControl < (23 - substr($timeStart, 0, 2))) 
This is because the system want to sub timeStart (In HOUR)  by 23, but that system returning both hour and minutes.

**Comment by bobkee** [comment] 2017-11-18 02:36
thank you!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by SKuipers** [comment] 2017-11-20 00:30
Thanks @luminkhant, well spotted! 😃 Would you be interested in submitting a pull request for your fix? Otherwise we'll be sure to apply your fix to v15.

**Comment by luminkhant** [comment] 2017-11-23 03:04
It's fine for me. you can apply that fix to v15 @SKuipers

**Comment by rossdotparker** [comment] 2017-11-27 13:32
Hello everyone, thanks for all of your contributions to identifying and fixing this issue. Sandra has created a PR to fix this one in v15, and it has now been merged into the codebase:

https://github.com/GibbonEdu/core/pull/419

Thanks again! Ross

**Closed by rossdotparker** 2017-11-27 13:32 UTC
