### ISSUE TITLE
Import from File not detecting custom YMLs

### ISSUE THREAD

**Issue by thecompman** [GibbonEdu/core#1391] opened 2021-08-01 17:07 UTC
**Describe the bug**
I wanted to set up a custom YML for importing some student application data. When I uploaded the custom yml file to both the resources/imports directory and also the uploads/imports directory, Gibbon did not detect it nor list it on the Import from File page.

**To Reproduce**

Using Gibbon 22.0, place a custom YML import file in the resources/imports directory or the uploads/imports directory
Go to System Admin / Import from File
Custom Import is not listed

**Expected behavior**
Custom YML import file should be listed at the top of the page

**Your System**

Gibbon version [e.g. v22.0.00]
PHP 7.3 

**Additional context**
After digging through the code, it seems that Gibbon is still looking for the old Data Admin/importcustomfolderlocation setting from the database to know where to look for custom import yml files. You can see this by looking at the function in the ImportType.php file. This setting no longer exists in the database because the Data Admin was moved to the core with v22.

After adding the Data Admin/importcustomfolderlocation setting back to the gibbonSetting table in the database, my custom YML file was recognized just fine and showed up properly on the Import from File page.

Perhaps this needs to be a setting that we can add through the GUI again or perhaps it needs to be hard coded to look in uploads/imports for custom YML files.

**Comment by SKuipers** [comment] 2021-08-30 06:05
Aha, thanks for sharing this detailed bug report, I think I know what the issue is. The functionality for importing was initially added in a separate Data Admin, and a few versions ago we moved it into the core. It looks like this setting may not have been moved across, but we didn't notice because we still had the Data Admin module installed. I've just PRd a fix for this for v23.

**Closed** 2021-08-31 03:17 UTC
Labels: bug
