### ISSUE TITLE
Error updating Reporting Cycle

### ISSUE THREAD

**Issue by tr-j** [GibbonEdu/core#1378] opened 2021-07-04 10:06 UTC
**Describe the bug**
On an existing reporting cycle, I attempted to update the end date and could not due to an error.

**To Reproduce**

1. Assess / Reports / Manage Reporting Cycles 
2. Save
3. Resulting in a blank screen
4. In error log:
`
PHP Fatal error:  Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, string given in /home/gibbon/public_html/modules/Reports/reporting_cycles_manage_editProcess.php:58
Stack trace:
#0 /home/gibbon/public_html/modules/Reports/reporting_cycles_manage_editProcess.php(58): array_map(Object(Closure), '')
#1 {main}
  thrown in /home/gibbon/public_html/modules/Reports/reporting_cycles_manage_editProcess.php on line 58
`

**Expected behavior**
It should save normally. I believe the issue is related to milestones, but I'm not sure why it just appeared. We do not have milestones on this reporting cycle.

This bypassed the error successfully (but it doesn't fix the error it just bypasses milestones altogether):
reporting_cycles_manage_editProcess.php, line 54:

`    // Sort and save milestones as a JSON blob`
`/*    $data['milestones'] = array_map(function ($item) {`
`        $item['milestoneDate'] = Format::dateConvert($item['milestoneDate']);`
`        return $item;`
`    }, $data['milestones']);`
`    $data['milestones'] = array_combine(array_keys($_POST['order']), array_values($data['milestones']));`
`    ksort($data['milestones']);`
`    $data['milestones'] = json_encode($data['milestones']);`
`    */`
`    $data['milestones'] = json_encode(array());`

**Your System**

 - Gibbon version 22.0

**Comment by SKuipers** [comment] 2021-07-04 12:05
Hi @tr-j, thanks for sharing this error report with us. I've taken a look and I was unable to reproduce the error. One thing to note is that Gibbon as of v22 requires PHP 7.3+. I wonder what version of PHP and MySQL you're running. Also, be sure to check the System Check page to see if all extensions are running. Another thing to check is any local browser extensions that may occasionally interfere with JavaScript (sometimes adblockers can be overzealous). Let us know what you find. Thanks!

**Comment by tr-j** [comment] 2021-07-04 12:42
Hi,
I read this in the change log and used PHP 8: On the technical side, v22 includes PHP 8 support, increases the minimum PHP version to 7.3, and includes a number of structural changes to the database.

I just swapped between 8.0 and 7.3 and under 7.3 there is no error, and on 8.0 I get the error (blank page). It appears to work fine on 7.3.

**Comment by yookoala** [comment] 2021-07-05 00:54
@tr-j: Can you please try to modify line 48 from this:

```
        'milestones'            => $_POST['milestones'] ?? '',
```

to this:
```
        'milestones'            => $_POST['milestones'] ?? [],
```

See if it fixes the error.

**Comment by tr-j** [comment] 2021-07-05 04:41
Hi Sandra,

I believe that helps, but it appears to require one more correction to the order as well (59).

$data['milestones'] = array_combine(array_keys($_POST['order']?? []), array_values($data['milestones']));

However, this error only appears using PHP 8.0. On 7.3 it's fine without the changes. With both of the changes it goes through, but I didn't test it using milestones in order to confirm that that section was working.

Thanks.

**Comment by yookoala** [comment] 2021-07-05 05:25
@tr-j: Thanks. Just updated the PR to include the line.
@SKuipers: Please check the PR. You may also want to include this in v23.0.00.

**Comment by SKuipers** [comment] 2021-08-23 01:15
Thanks for the fix @yookoala, I've merged it in. @tr-j, this issue should now be resolved, you can apply the same changed back to v22 to patch your system. Thanks for helping us to improve the system 👍

**Closed by SKuipers** 2021-08-23 01:15 UTC
